image: registry.mpi-sws.org/osnet-latex-dev

stages:
  - build
  - test

build_a:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - paper.pdf

spellcheck:
  stage: test
  script:
    - make check TEXIDOTE_EXTRA=--ci
    - make check-html TEXIDOTE_EXTRA=--ci
  artifacts:
    paths:
      - spellcheck.html
